export const defaultCategories = [
  {
    name: "Clothing & Apparel",
    slug: "clothing-apparel",
    parentCategory: null,
    status: "active",
    sortOrder: 0,
    metaTitle: "Clothing & Apparel",
    metaDescription: "Clothing & Apparel Category",
    image: "/images/clothing-apparel.jpg",
    subCategories: [
      {
        name: "Men's Clothing",
        slug: "mens-clothing",
        parentCategory: "Clothing & Apparel",
        status: "active",
        sortOrder: 1,
        metaTitle: "Men's Clothing",
        metaDescription: "Men's Clothing Category",
        image: "/images/mens-clothing.jpg",
        subCategories: [
          {
            name: "Shirts",
            slug: "mens-shirts",
            parentCategory: "Men's Clothing",
            status: "active",
            sortOrder: 1,
            metaTitle: "Shirts",
            metaDescription: "Men's Shirts",
            image: "/images/mens-shirts.jpg",
            subCategories: [
              { name: "T-Shirts", slug: "mens-t-shirts" },
              { name: "Polo Shirts", slug: "mens-polo-shirts" },
              { name: "Dress Shirts", slug: "mens-dress-shirts" },
              { name: "Casual Shirts", slug: "mens-casual-shirts" },
            ],
          },
          {
            name: "Trousers",
            slug: "mens-trousers",
            parentCategory: "Men's Clothing",
            status: "active",
            sortOrder: 2,
            metaTitle: "Trousers",
            metaDescription: "Men's Trousers",
            image: "/images/mens-trousers.jpg",
            subCategories: [
              { name: "Jeans", slug: "mens-jeans" },
              { name: "Chinos", slug: "mens-chinos" },
              { name: "Dress Pants", slug: "mens-dress-pants" },
              { name: "Cargo Pants", slug: "mens-cargo-pants" },
            ],
          },
          {
            name: "Suits & Blazers",
            slug: "mens-suits-blazers",
            parentCategory: "Men's Clothing",
            status: "active",
            sortOrder: 3,
            metaTitle: "Suits & Blazers",
            metaDescription: "Men's Suits & Blazers",
            image: "/images/mens-suits.jpg",
            subCategories: [
              { name: "Business Suits", slug: "mens-business-suits" },
              { name: "Blazers", slug: "mens-blazers" },
              { name: "Tuxedos", slug: "mens-tuxedos" },
              { name: "Waistcoats", slug: "mens-waistcoats" },
            ],
          },
          {
            name: "Outerwear",
            slug: "mens-outerwear",
            parentCategory: "Men's Clothing",
            status: "active",
            sortOrder: 4,
            metaTitle: "Outerwear",
            metaDescription: "Men's Outerwear",
            image: "/images/mens-outerwear.jpg",
            subCategories: [
              { name: "Jackets", slug: "mens-jackets" },
              { name: "Coats", slug: "mens-coats" },
              { name: "Parkas", slug: "mens-parkas" },
              { name: "Leather Jackets", slug: "mens-leather-jackets" },
            ],
          },
          {
            name: "Activewear",
            slug: "mens-activewear",
            parentCategory: "Men's Clothing",
            status: "active",
            sortOrder: 5,
            metaTitle: "Activewear",
            metaDescription: "Men's Activewear",
            image: "/images/mens-activewear.jpg",
            subCategories: [
              { name: "Gym Wear", slug: "mens-gym-wear" },
              { name: "Running Wear", slug: "mens-running-wear" },
              { name: "Training Shorts", slug: "mens-training-shorts" },
            ],
          },
          {
            name: "Underwear & Socks",
            slug: "mens-underwear-socks",
            parentCategory: "Men's Clothing",
            status: "active",
            sortOrder: 6,
            metaTitle: "Underwear & Socks",
            metaDescription: "Men's Underwear & Socks",
            image: "/images/mens-underwear.jpg",
            subCategories: [
              { name: "Boxers", slug: "mens-boxers" },
              { name: "Briefs", slug: "mens-briefs" },
              { name: "Socks", slug: "mens-socks" },
              { name: "Thermal Underwear", slug: "mens-thermal-underwear" },
            ],
          },
          {
            name: "Swimwear",
            slug: "mens-swimwear",
            parentCategory: "Men's Clothing",
            status: "active",
            sortOrder: 7,
            metaTitle: "Swimwear",
            metaDescription: "Men's Swimwear",
            image: "/images/mens-swimwear.jpg",
            subCategories: [
              { name: "Swim Shorts", slug: "mens-swim-shorts" },
              { name: "Rash Guards", slug: "mens-rash-guards" },
            ],
          },
        ],
      },
      {
        name: "Women's Clothing",
        slug: "womens-clothing",
        parentCategory: "Clothing & Apparel",
        status: "active",
        sortOrder: 2,
        metaTitle: "Women's Clothing",
        metaDescription: "Women's Clothing Category",
        image: "/images/womens-clothing.jpg",
        subCategories: [
          {
            name: "Dresses",
            slug: "womens-dresses",
            parentCategory: "Women's Clothing",
            status: "active",
            sortOrder: 1,
            metaTitle: "Dresses",
            metaDescription: "Women's Dresses",
            image: "/images/womens-dresses.jpg",
            subCategories: [
              { name: "Casual Dresses", slug: "womens-casual-dresses" },
              { name: "Evening Dresses", slug: "womens-evening-dresses" },
              { name: "Summer Dresses", slug: "womens-summer-dresses" },
              { name: "Maxi Dresses", slug: "womens-maxi-dresses" },
            ],
          },
          {
            name: "Tops & Blouses",
            slug: "womens-tops-blouses",
            parentCategory: "Women's Clothing",
            status: "active",
            sortOrder: 2,
            metaTitle: "Tops & Blouses",
            metaDescription: "Women's Tops & Blouses",
            image: "/images/womens-tops.jpg",
            subCategories: [
              { name: "T-Shirts", slug: "womens-t-shirts" },
              { name: "Blouses", slug: "womens-blouses" },
              { name: "Tank Tops", slug: "womens-tank-tops" },
              { name: "Sweaters", slug: "womens-sweaters" },
            ],
          },
          {
            name: "Bottoms",
            slug: "womens-bottoms",
            parentCategory: "Women's Clothing",
            status: "active",
            sortOrder: 3,
            metaTitle: "Bottoms",
            metaDescription: "Women's Bottoms",
            image: "/images/womens-bottoms.jpg",
            subCategories: [
              { name: "Jeans", slug: "womens-jeans" },
              { name: "Leggings", slug: "womens-leggings" },
              { name: "Skirts", slug: "womens-skirts" },
              { name: "Shorts", slug: "womens-shorts" },
              { name: "Trousers", slug: "womens-trousers" },
            ],
          },
          {
            name: "Outerwear",
            slug: "womens-outerwear",
            parentCategory: "Women's Clothing",
            status: "active",
            sortOrder: 4,
            metaTitle: "Outerwear",
            metaDescription: "Women's Outerwear",
            image: "/images/womens-outerwear.jpg",
            subCategories: [
              { name: "Jackets", slug: "womens-jackets" },
              { name: "Coats", slug: "womens-coats" },
              { name: "Blazers", slug: "womens-blazers" },
              { name: "Leather Jackets", slug: "womens-leather-jackets" },
            ],
          },
          {
            name: "Activewear",
            slug: "womens-activewear",
            parentCategory: "Women's Clothing",
            status: "active",
            sortOrder: 5,
            metaTitle: "Activewear",
            metaDescription: "Women's Activewear",
            image: "/images/womens-activewear.jpg",
            subCategories: [
              { name: "Sports Bras", slug: "womens-sports-bras" },
              { name: "Leggings", slug: "womens-athletic-leggings" },
              { name: "Workout Tops", slug: "womens-workout-tops" },
            ],
          },
          {
            name: "Lingerie & Sleepwear",
            slug: "womens-lingerie-sleepwear",
            parentCategory: "Women's Clothing",
            status: "active",
            sortOrder: 6,
            metaTitle: "Lingerie & Sleepwear",
            metaDescription: "Women's Lingerie & Sleepwear",
            image: "/images/womens-lingerie.jpg",
            subCategories: [
              { name: "Bras", slug: "womens-bras" },
              { name: "Panties", slug: "womens-panties" },
              { name: "Sleepwear", slug: "womens-sleepwear" },
              { name: "Robes", slug: "womens-robes" },
            ],
          },
          {
            name: "Swimwear",
            slug: "womens-swimwear",
            parentCategory: "Women's Clothing",
            status: "active",
            sortOrder: 7,
            metaTitle: "Swimwear",
            metaDescription: "Women's Swimwear",
            image: "/images/womens-swimwear.jpg",
            subCategories: [
              { name: "Bikinis", slug: "womens-bikinis" },
              {
                name: "One-Piece Swimsuits",
                slug: "womens-one-piece-swimsuits",
              },
              { name: "Cover-Ups", slug: "womens-swim-cover-ups" },
            ],
          },
        ],
      },
      {
        name: "Kids' Clothing",
        slug: "kids-clothing",
        parentCategory: "Clothing & Apparel",
        status: "active",
        sortOrder: 3,
        metaTitle: "Kids' Clothing",
        metaDescription: "Kids' Clothing Category",
        image: "/images/kids-clothing.jpg",
        subCategories: [
          {
            name: "Boys' Clothing",
            slug: "boys-clothing",
            parentCategory: "Kids' Clothing",
            status: "active",
            sortOrder: 1,
            metaTitle: "Boys' Clothing",
            metaDescription: "Boys' Clothing",
            image: "/images/boys-clothing.jpg",
            subCategories: [
              { name: "T-Shirts & Tops", slug: "boys-t-shirts-tops" },
              { name: "Jeans & Pants", slug: "boys-jeans-pants" },
              { name: "Shorts", slug: "boys-shorts" },
              {
                name: "Hoodies & Sweatshirts",
                slug: "boys-hoodies-sweatshirts",
              },
            ],
          },
          {
            name: "Girls' Clothing",
            slug: "girls-clothing",
            parentCategory: "Kids' Clothing",
            status: "active",
            sortOrder: 2,
            metaTitle: "Girls' Clothing",
            metaDescription: "Girls' Clothing",
            image: "/images/girls-clothing.jpg",
            subCategories: [
              { name: "Dresses", slug: "girls-dresses" },
              { name: "Tops", slug: "girls-tops" },
              { name: "Leggings", slug: "girls-leggings" },
              { name: "Skirts", slug: "girls-skirts" },
            ],
          },
          {
            name: "Baby Clothing",
            slug: "baby-clothing",
            parentCategory: "Kids' Clothing",
            status: "active",
            sortOrder: 3,
            metaTitle: "Baby Clothing",
            metaDescription: "Baby Clothing",
            image: "/images/baby-clothing.jpg",
            subCategories: [
              { name: "Bodysuits", slug: "baby-bodysuits" },
              { name: "Rompers", slug: "baby-rompers" },
              { name: "Sleepwear", slug: "baby-sleepwear" },
              { name: "Sets", slug: "baby-clothing-sets" },
            ],
          },
          {
            name: "Kids' Outerwear",
            slug: "kids-outerwear",
            parentCategory: "Kids' Clothing",
            status: "active",
            sortOrder: 4,
            metaTitle: "Kids' Outerwear",
            metaDescription: "Kids' Outerwear",
            image: "/images/kids-outerwear.jpg",
            subCategories: [
              { name: "Jackets", slug: "kids-jackets" },
              { name: "Coats", slug: "kids-coats" },
              { name: "Rainwear", slug: "kids-rainwear" },
            ],
          },
          {
            name: "Kids' Accessories",
            slug: "kids-accessories",
            parentCategory: "Kids' Clothing",
            status: "active",
            sortOrder: 5,
            metaTitle: "Kids' Accessories",
            metaDescription: "Kids' Accessories",
            image: "/images/kids-accessories.jpg",
            subCategories: [
              { name: "Hats", slug: "kids-hats" },
              { name: "Gloves", slug: "kids-gloves" },
              { name: "Scarves", slug: "kids-scarves" },
            ],
          },
        ],
      },
      {
        name: "Footwear",
        slug: "footwear",
        parentCategory: "Clothing & Apparel",
        status: "active",
        sortOrder: 4,
        metaTitle: "Footwear",
        metaDescription: "Footwear Category",
        image: "/images/footwear.jpg",
        subCategories: [
          {
            name: "Men's Shoes",
            slug: "mens-shoes",
            parentCategory: "Footwear",
            status: "active",
            sortOrder: 1,
            metaTitle: "Men's Shoes",
            metaDescription: "Men's Shoes",
            image: "/images/mens-shoes.jpg",
            subCategories: [
              { name: "Sneakers", slug: "mens-sneakers" },
              { name: "Boots", slug: "mens-boots" },
              { name: "Dress Shoes", slug: "mens-dress-shoes" },
              { name: "Sandals", slug: "mens-sandals" },
              { name: "Loafers", slug: "mens-loafers" },
            ],
          },
          {
            name: "Women's Shoes",
            slug: "womens-shoes",
            parentCategory: "Footwear",
            status: "active",
            sortOrder: 2,
            metaTitle: "Women's Shoes",
            metaDescription: "Women's Shoes",
            image: "/images/womens-shoes.jpg",
            subCategories: [
              { name: "Heels", slug: "womens-heels" },
              { name: "Flats", slug: "womens-flats" },
              { name: "Boots", slug: "womens-boots" },
              { name: "Sneakers", slug: "womens-sneakers" },
              { name: "Sandals", slug: "womens-sandals" },
            ],
          },
          {
            name: "Kids' Shoes",
            slug: "kids-shoes",
            parentCategory: "Footwear",
            status: "active",
            sortOrder: 3,
            metaTitle: "Kids' Shoes",
            metaDescription: "Kids' Shoes",
            image: "/images/kids-shoes.jpg",
            subCategories: [
              { name: "Sneakers", slug: "kids-sneakers" },
              { name: "Sandals", slug: "kids-sandals" },
              { name: "Boots", slug: "kids-boots" },
              { name: "School Shoes", slug: "kids-school-shoes" },
            ],
          },
          {
            name: "Athletic Shoes",
            slug: "athletic-shoes",
            parentCategory: "Footwear",
            status: "active",
            sortOrder: 4,
            metaTitle: "Athletic Shoes",
            metaDescription: "Athletic Shoes",
            image: "/images/athletic-shoes.jpg",
            subCategories: [
              { name: "Running Shoes", slug: "running-shoes" },
              { name: "Basketball Shoes", slug: "basketball-shoes" },
              { name: "Training Shoes", slug: "training-shoes" },
              { name: "Hiking Shoes", slug: "hiking-shoes" },
            ],
          },
        ],
      },
      {
        name: "Accessories",
        slug: "accessories",
        parentCategory: "Clothing & Apparel",
        status: "active",
        sortOrder: 5,
        metaTitle: "Accessories",
        metaDescription: "Accessories Category",
        image: "/images/accessories.jpg",
        subCategories: [
          {
            name: "Bags",
            slug: "bags",
            parentCategory: "Accessories",
            status: "active",
            sortOrder: 1,
            metaTitle: "Bags",
            metaDescription: "Bags",
            image: "/images/bags.jpg",
            subCategories: [
              { name: "Backpacks", slug: "backpacks" },
              { name: "Handbags", slug: "handbags" },
              { name: "Tote Bags", slug: "tote-bags" },
              { name: "Travel Bags", slug: "travel-bags" },
            ],
          },
          {
            name: "Watches",
            slug: "watches",
            parentCategory: "Accessories",
            status: "active",
            sortOrder: 2,
            metaTitle: "Watches",
            metaDescription: "Watches",
            image: "/images/watches.jpg",
            subCategories: [
              { name: "Men's Watches", slug: "mens-watches" },
              { name: "Women's Watches", slug: "womens-watches" },
              { name: "Smartwatches", slug: "smartwatches" },
            ],
          },
          {
            name: "Jewelry",
            slug: "jewelry",
            parentCategory: "Accessories",
            status: "active",
            sortOrder: 3,
            metaTitle: "Jewelry",
            metaDescription: "Jewelry",
            image: "/images/jewelry.jpg",
            subCategories: [
              { name: "Necklaces", slug: "necklaces" },
              { name: "Earrings", slug: "earrings" },
              { name: "Bracelets", slug: "bracelets" },
              { name: "Rings", slug: "rings" },
            ],
          },
          {
            name: "Hats & Caps",
            slug: "hats-caps",
            parentCategory: "Accessories",
            status: "active",
            sortOrder: 4,
            metaTitle: "Hats & Caps",
            metaDescription: "Hats & Caps",
            image: "/images/hats-caps.jpg",
            subCategories: [
              { name: "Baseball Caps", slug: "baseball-caps" },
              { name: "Beanies", slug: "beanies" },
              { name: "Sun Hats", slug: "sun-hats" },
            ],
          },
          {
            name: "Belts",
            slug: "belts",
            parentCategory: "Accessories",
            status: "active",
            sortOrder: 5,
            metaTitle: "Belts",
            metaDescription: "Belts",
            image: "/images/belts.jpg",
          },
          {
            name: "Sunglasses",
            slug: "sunglasses",
            parentCategory: "Accessories",
            status: "active",
            sortOrder: 6,
            metaTitle: "Sunglasses",
            metaDescription: "Sunglasses",
            image: "/images/sunglasses.jpg",
          },
        ],
      },
    ],
  },
  {
    name: "Electronics",
    slug: "electronics",
    parentCategory: null,
    status: "active",
    sortOrder: 1,
    metaTitle: "Electronics",
    metaDescription: "Electronics Category",
    image: "/images/electronics.jpg",
    subCategories: [
      {
        name: "Computers & Laptops",
        slug: "computers-laptops",
        parentCategory: "Electronics",
        status: "active",
        sortOrder: 1,
        metaTitle: "Computers & Laptops",
        metaDescription: "Computers & Laptops Category",
        image: "/images/computers-laptops.jpg",
        subCategories: [
          {
            name: "Laptops",
            slug: "laptops",
            parentCategory: "Computers & Laptops",
            status: "active",
            sortOrder: 1,
            metaTitle: "Laptops",
            metaDescription: "Laptops",
            image: "/images/laptops.jpg",
            subCategories: [
              { name: "Ultrabooks", slug: "ultrabooks" },
              { name: "Gaming Laptops", slug: "gaming-laptops" },
              { name: "Business Laptops", slug: "business-laptops" },
              { name: "2-in-1 Laptops", slug: "2-in-1-laptops" },
            ],
          },
          {
            name: "Desktops",
            slug: "desktops",
            parentCategory: "Computers & Laptops",
            status: "active",
            sortOrder: 2,
            metaTitle: "Desktops",
            metaDescription: "Desktops",
            image: "/images/desktops.jpg",
            subCategories: [
              { name: "All-in-One PCs", slug: "all-in-one-pcs" },
              { name: "Gaming Desktops", slug: "gaming-desktops" },
              { name: "Workstations", slug: "workstations" },
            ],
          },
          {
            name: "Tablets",
            slug: "tablets",
            parentCategory: "Computers & Laptops",
            status: "active",
            sortOrder: 3,
            metaTitle: "Tablets",
            metaDescription: "Tablets",
            image: "/images/tablets.jpg",
            subCategories: [
              { name: "Android Tablets", slug: "android-tablets" },
              { name: "iPad", slug: "ipad" },
              { name: "Windows Tablets", slug: "windows-tablets" },
            ],
          },
          {
            name: "Computer Accessories",
            slug: "computer-accessories",
            parentCategory: "Computers & Laptops",
            status: "active",
            sortOrder: 4,
            metaTitle: "Computer Accessories",
            metaDescription: "Computer Accessories",
            image: "/images/computer-accessories.jpg",
            subCategories: [
              { name: "Keyboards", slug: "keyboards" },
              { name: "Mice", slug: "mice" },
              { name: "Monitors", slug: "monitors" },
              { name: "External Storage", slug: "external-storage" },
            ],
          },
          {
            name: "Printers & Scanners",
            slug: "printers-scanners",
            parentCategory: "Computers & Laptops",
            status: "active",
            sortOrder: 5,
            metaTitle: "Printers & Scanners",
            metaDescription: "Printers & Scanners",
            image: "/images/printers-scanners.jpg",
            subCategories: [
              { name: "Inkjet Printers", slug: "inkjet-printers" },
              { name: "Laser Printers", slug: "laser-printers" },
              { name: "All-in-One Printers", slug: "all-in-one-printers" },
            ],
          },
        ],
      },
      {
        name: "Smartphones & Accessories",
        slug: "smartphones-accessories",
        parentCategory: "Electronics",
        status: "active",
        sortOrder: 2,
        metaTitle: "Smartphones & Accessories",
        metaDescription: "Smartphones & Accessories Category",
        image: "/images/smartphones-accessories.jpg",
        subCategories: [
          {
            name: "Smartphones",
            slug: "smartphones",
            parentCategory: "Smartphones & Accessories",
            status: "active",
            sortOrder: 1,
            metaTitle: "Smartphones",
            metaDescription: "Smartphones",
            image: "/images/smartphones.jpg",
            subCategories: [
              { name: "Android Phones", slug: "android-phones" },
              { name: "iPhones", slug: "iphones" },
              { name: "Budget Phones", slug: "budget-phones" },
              { name: "Flagship Phones", slug: "flagship-phones" },
            ],
          },
          {
            name: "Phone Cases",
            slug: "phone-cases",
            parentCategory: "Smartphones & Accessories",
            status: "active",
            sortOrder: 2,
            metaTitle: "Phone Cases",
            metaDescription: "Phone Cases",
            image: "/images/phone-cases.jpg",
            subCategories: [
              { name: "Protective Cases", slug: "protective-cases" },
              { name: "Wallet Cases", slug: "wallet-cases" },
              { name: "Designer Cases", slug: "designer-cases" },
            ],
          },
          {
            name: "Chargers & Cables",
            slug: "chargers-cables",
            parentCategory: "Smartphones & Accessories",
            status: "active",
            sortOrder: 3,
            metaTitle: "Chargers & Cables",
            metaDescription: "Chargers & Cables",
            image: "/images/chargers-cables.jpg",
            subCategories: [
              { name: "Wireless Chargers", slug: "wireless-chargers" },
              { name: "Fast Chargers", slug: "fast-chargers" },
              { name: "USB Cables", slug: "usb-cables" },
            ],
          },
          {
            name: "Screen Protectors",
            slug: "screen-protectors",
            parentCategory: "Smartphones & Accessories",
            status: "active",
            sortOrder: 4,
            metaTitle: "Screen Protectors",
            metaDescription: "Screen Protectors",
            image: "/images/screen-protectors.jpg",
          },
          {
            name: "Power Banks",
            slug: "power-banks",
            parentCategory: "Smartphones & Accessories",
            status: "active",
            sortOrder: 5,
            metaTitle: "Power Banks",
            metaDescription: "Power Banks",
            image: "/images/power-banks.jpg",
          },
        ],
      },
      {
        name: "TVs & Home Theater",
        slug: "tvs-home-theater",
        parentCategory: "Electronics",
        status: "active",
        sortOrder: 3,
        metaTitle: "TVs & Home Theater",
        metaDescription: "TVs & Home Theater Category",
        image: "/images/tvs-home-theater.jpg",
        subCategories: [
          {
            name: "Televisions",
            slug: "televisions",
            parentCategory: "TVs & Home Theater",
            status: "active",
            sortOrder: 1,
            metaTitle: "Televisions",
            metaDescription: "Televisions",
            image: "/images/televisions.jpg",
            subCategories: [
              { name: "LED TVs", slug: "led-tvs" },
              { name: "OLED TVs", slug: "oled-tvs" },
              { name: "QLED TVs", slug: "qled-tvs" },
              { name: "Smart TVs", slug: "smart-tvs" },
            ],
          },
          {
            name: "Home Theater Systems",
            slug: "home-theater-systems",
            parentCategory: "TVs & Home Theater",
            status: "active",
            sortOrder: 2,
            metaTitle: "Home Theater Systems",
            metaDescription: "Home Theater Systems",
            image: "/images/home-theater-systems.jpg",
          },
          {
            name: "Soundbars",
            slug: "soundbars",
            parentCategory: "TVs & Home Theater",
            status: "active",
            sortOrder: 3,
            metaTitle: "Soundbars",
            metaDescription: "Soundbars",
            image: "/images/soundbars.jpg",
          },
          {
            name: "Projectors",
            slug: "projectors",
            parentCategory: "TVs & Home Theater",
            status: "active",
            sortOrder: 4,
            metaTitle: "Projectors",
            metaDescription: "Projectors",
            image: "/images/projectors.jpg",
          },
          {
            name: "TV Mounts & Stands",
            slug: "tv-mounts-stands",
            parentCategory: "TVs & Home Theater",
            status: "active",
            sortOrder: 5,
            metaTitle: "TV Mounts & Stands",
            metaDescription: "TV Mounts & Stands",
            image: "/images/tv-mounts-stands.jpg",
          },
        ],
      },
      {
        name: "Audio",
        slug: "audio",
        parentCategory: "Electronics",
        status: "active",
        sortOrder: 4,
        metaTitle: "Audio",
        metaDescription: "Audio Category",
        image: "/images/audio.jpg",
        subCategories: [
          {
            name: "Headphones",
            slug: "headphones",
            parentCategory: "Audio",
            status: "active",
            sortOrder: 1,
            metaTitle: "Headphones",
            metaDescription: "Headphones",
            image: "/images/headphones.jpg",
            subCategories: [
              { name: "Wireless Headphones", slug: "wireless-headphones" },
              {
                name: "Noise-Cancelling Headphones",
                slug: "noise-cancelling-headphones",
              },
              { name: "Earbuds", slug: "earbuds" },
              { name: "Gaming Headsets", slug: "gaming-headsets" },
            ],
          },
          {
            name: "Speakers",
            slug: "speakers",
            parentCategory: "Audio",
            status: "active",
            sortOrder: 2,
            metaTitle: "Speakers",
            metaDescription: "Speakers",
            image: "/images/speakers.jpg",
            subCategories: [
              { name: "Bluetooth Speakers", slug: "bluetooth-speakers" },
              { name: "Smart Speakers", slug: "smart-speakers" },
              { name: "Portable Speakers", slug: "portable-speakers" },
            ],
          },
          {
            name: "Home Audio",
            slug: "home-audio",
            parentCategory: "Audio",
            status: "active",
            sortOrder: 3,
            metaTitle: "Home Audio",
            metaDescription: "Home Audio",
            image: "/images/home-audio.jpg",
          },
        ],
      },
      {
        name: "Cameras & Photography",
        slug: "cameras-photography",
        parentCategory: "Electronics",
        status: "active",
        sortOrder: 5,
        metaTitle: "Cameras & Photography",
        metaDescription: "Cameras & Photography Category",
        image: "/images/cameras-photography.jpg",
        subCategories: [
          {
            name: "Digital Cameras",
            slug: "digital-cameras",
            parentCategory: "Cameras & Photography",
            status: "active",
            sortOrder: 1,
            metaTitle: "Digital Cameras",
            metaDescription: "Digital Cameras",
            image: "/images/digital-cameras.jpg",
            subCategories: [
              { name: "DSLR Cameras", slug: "dslr-cameras" },
              { name: "Mirrorless Cameras", slug: "mirrorless-cameras" },
              { name: "Compact Cameras", slug: "compact-cameras" },
            ],
          },
          {
            name: "Lenses",
            slug: "lenses",
            parentCategory: "Cameras & Photography",
            status: "active",
            sortOrder: 2,
            metaTitle: "Lenses",
            metaDescription: "Lenses",
            image: "/images/lenses.jpg",
          },
          {
            name: "Camera Accessories",
            slug: "camera-accessories",
            parentCategory: "Cameras & Photography",
            status: "active",
            sortOrder: 3,
            metaTitle: "Camera Accessories",
            metaDescription: "Camera Accessories",
            image: "/images/camera-accessories.jpg",
            subCategories: [
              { name: "Tripods", slug: "tripods" },
              { name: "Camera Bags", slug: "camera-bags" },
              { name: "Memory Cards", slug: "memory-cards" },
            ],
          },
          {
            name: "Drones",
            slug: "drones",
            parentCategory: "Cameras & Photography",
            status: "active",
            sortOrder: 4,
            metaTitle: "Drones",
            metaDescription: "Drones",
            image: "/images/drones.jpg",
          },
        ],
      },
      {
        name: "Gaming",
        slug: "gaming",
        parentCategory: "Electronics",
        status: "active",
        sortOrder: 6,
        metaTitle: "Gaming",
        metaDescription: "Gaming Category",
        image: "/images/gaming.jpg",
        subCategories: [
          {
            name: "Gaming Consoles",
            slug: "gaming-consoles",
            parentCategory: "Gaming",
            status: "active",
            sortOrder: 1,
            metaTitle: "Gaming Consoles",
            metaDescription: "Gaming Consoles",
            image: "/images/gaming-consoles.jpg",
            subCategories: [
              { name: "PlayStation", slug: "playstation" },
              { name: "Xbox", slug: "xbox" },
              { name: "Nintendo", slug: "nintendo" },
            ],
          },
          {
            name: "Games",
            slug: "games",
            parentCategory: "Gaming",
            status: "active",
            sortOrder: 2,
            metaTitle: "Games",
            metaDescription: "Games",
            image: "/images/games.jpg",
            subCategories: [
              { name: "PC Games", slug: "pc-games" },
              { name: "Console Games", slug: "console-games" },
              { name: "VR Games", slug: "vr-games" },
            ],
          },
          {
            name: "Gaming Accessories",
            slug: "gaming-accessories",
            parentCategory: "Gaming",
            status: "active",
            sortOrder: 3,
            metaTitle: "Gaming Accessories",
            metaDescription: "Gaming Accessories",
            image: "/images/gaming-accessories.jpg",
            subCategories: [
              { name: "Controllers", slug: "controllers" },
              { name: "Gaming Headsets", slug: "gaming-headsets" },
              { name: "Gaming Keyboards", slug: "gaming-keyboards" },
            ],
          },
          {
            name: "VR Headsets",
            slug: "vr-headsets",
            parentCategory: "Gaming",
            status: "active",
            sortOrder: 4,
            metaTitle: "VR Headsets",
            metaDescription: "VR Headsets",
            image: "/images/vr-headsets.jpg",
          },
        ],
      },
      {
        name: "Smart Home",
        slug: "smart-home",
        parentCategory: "Electronics",
        status: "active",
        sortOrder: 7,
        metaTitle: "Smart Home",
        metaDescription: "Smart Home Category",
        image: "/images/smart-home.jpg",
        subCategories: [
          {
            name: "Smart Speakers",
            slug: "smart-speakers",
            parentCategory: "Smart Home",
            status: "active",
            sortOrder: 1,
            metaTitle: "Smart Speakers",
            metaDescription: "Smart Speakers",
            image: "/images/smart-speakers.jpg",
          },
          {
            name: "Smart Lighting",
            slug: "smart-lighting",
            parentCategory: "Smart Home",
            status: "active",
            sortOrder: 2,
            metaTitle: "Smart Lighting",
            metaDescription: "Smart Lighting",
            image: "/images/smart-lighting.jpg",
          },
          {
            name: "Smart Security",
            slug: "smart-security",
            parentCategory: "Smart Home",
            status: "active",
            sortOrder: 3,
            metaTitle: "Smart Security",
            metaDescription: "Smart Security",
            image: "/images/smart-security.jpg",
            subCategories: [
              { name: "Security Cameras", slug: "security-cameras" },
              { name: "Smart Locks", slug: "smart-locks" },
            ],
          },
          {
            name: "Smart Thermostats",
            slug: "smart-thermostats",
            parentCategory: "Smart Home",
            status: "active",
            sortOrder: 4,
            metaTitle: "Smart Thermostats",
            metaDescription: "Smart Thermostats",
            image: "/images/smart-thermostats.jpg",
          },
        ],
      },
    ],
  },
  {
    name: "Home & Garden",
    slug: "home-garden",
    parentCategory: null,
    status: "active",
    sortOrder: 2,
    metaTitle: "Home & Garden",
    metaDescription: "Home & Garden Category",
    image: "/images/home-garden.jpg",
    subCategories: [
      {
        name: "Furniture",
        slug: "furniture",
        parentCategory: "Home & Garden",
        status: "active",
        sortOrder: 1,
        metaTitle: "Furniture",
        metaDescription: "Furniture Category",
        image: "/images/furniture.jpg",
        subCategories: [
          {
            name: "Living Room Furniture",
            slug: "living-room-furniture",
            parentCategory: "Furniture",
            status: "active",
            sortOrder: 1,
            metaTitle: "Living Room Furniture",
            metaDescription: "Living Room Furniture",
            image: "/images/living-room-furniture.jpg",
            subCategories: [
              { name: "Sofas", slug: "sofas" },
              { name: "Coffee Tables", slug: "coffee-tables" },
              { name: "TV Stands", slug: "tv-stands" },
            ],
          },
          {
            name: "Bedroom Furniture",
            slug: "bedroom-furniture",
            parentCategory: "Furniture",
            status: "active",
            sortOrder: 2,
            metaTitle: "Bedroom Furniture",
            metaDescription: "Bedroom Furniture",
            image: "/images/bedroom-furniture.jpg",
            subCategories: [
              { name: "Beds", slug: "beds" },
              { name: "Wardrobes", slug: "wardrobes" },
              { name: "Dressers", slug: "dressers" },
            ],
          },
          {
            name: "Dining Room Furniture",
            slug: "dining-room-furniture",
            parentCategory: "Furniture",
            status: "active",
            sortOrder: 3,
            metaTitle: "Dining Room Furniture",
            metaDescription: "Dining Room Furniture",
            image: "/images/dining-room-furniture.jpg",
            subCategories: [
              { name: "Dining Tables", slug: "dining-tables" },
              { name: "Dining Chairs", slug: "dining-chairs" },
              { name: "Buffets & Sideboards", slug: "buffets-sideboards" },
            ],
          },
          {
            name: "Home Office Furniture",
            slug: "home-office-furniture",
            parentCategory: "Furniture",
            status: "active",
            sortOrder: 4,
            metaTitle: "Home Office Furniture",
            metaDescription: "Home Office Furniture",
            image: "/images/home-office-furniture.jpg",
            subCategories: [
              { name: "Desks", slug: "desks" },
              { name: "Office Chairs", slug: "office-chairs" },
              { name: "Bookcases", slug: "bookcases" },
            ],
          },
          {
            name: "Storage Furniture",
            slug: "storage-furniture",
            parentCategory: "Furniture",
            status: "active",
            sortOrder: 5,
            metaTitle: "Storage Furniture",
            metaDescription: "Storage Furniture",
            image: "/images/storage-furniture.jpg",
            subCategories: [
              { name: "Shelving Units", slug: "shelving-units" },
              { name: "Cabinets", slug: "cabinets" },
              { name: "Chests", slug: "chests" },
            ],
          },
        ],
      },
      {
        name: "Home Decor",
        slug: "home-decor",
        parentCategory: "Home & Garden",
        status: "active",
        sortOrder: 2,
        metaTitle: "Home Decor",
        metaDescription: "Home Decor Category",
        image: "/images/home-decor.jpg",
        subCategories: [
          {
            name: "Wall Decor",
            slug: "wall-decor",
            parentCategory: "Home Decor",
            status: "active",
            sortOrder: 1,
            metaTitle: "Wall Decor",
            metaDescription: "Wall Decor",
            image: "/images/wall-decor.jpg",
            subCategories: [
              { name: "Wall Art", slug: "wall-art" },
              { name: "Mirrors", slug: "mirrors" },
              { name: "Wall Clocks", slug: "wall-clocks" },
            ],
          },
          {
            name: "Decorative Accessories",
            slug: "decorative-accessories",
            parentCategory: "Home Decor",
            status: "active",
            sortOrder: 2,
            metaTitle: "Decorative Accessories",
            metaDescription: "Decorative Accessories",
            image: "/images/decorative-accessories.jpg",
            subCategories: [
              { name: "Vases", slug: "vases" },
              { name: "Candles", slug: "candles" },
              { name: "Figurines", slug: "figurines" },
            ],
          },
          {
            name: "Seasonal Decor",
            slug: "seasonal-decor",
            parentCategory: "Home Decor",
            status: "active",
            sortOrder: 3,
            metaTitle: "Seasonal Decor",
            metaDescription: "Seasonal Decor",
            image: "/images/seasonal-decor.jpg",
          },
          {
            name: "Rugs",
            slug: "rugs",
            parentCategory: "Home Decor",
            status: "active",
            sortOrder: 4,
            metaTitle: "Rugs",
            metaDescription: "Rugs",
            image: "/images/rugs.jpg",
            subCategories: [
              { name: "Area Rugs", slug: "area-rugs" },
              { name: "Door Mats", slug: "door-mats" },
              { name: "Runner Rugs", slug: "runner-rugs" },
            ],
          },
          {
            name: "Curtains & Blinds",
            slug: "curtains-blinds",
            parentCategory: "Home Decor",
            status: "active",
            sortOrder: 5,
            metaTitle: "Curtains & Blinds",
            metaDescription: "Curtains & Blinds",
            image: "/images/curtains-blinds.jpg",
          },
        ],
      },
      {
        name: "Kitchen & Dining",
        slug: "kitchen-dining",
        parentCategory: "Home & Garden",
        status: "active",
        sortOrder: 3,
        metaTitle: "Kitchen & Dining",
        metaDescription: "Kitchen & Dining Category",
        image: "/images/kitchen-dining.jpg",
        subCategories: [
          {
            name: "Cookware",
            slug: "cookware",
            parentCategory: "Kitchen & Dining",
            status: "active",
            sortOrder: 1,
            metaTitle: "Cookware",
            metaDescription: "Cookware",
            image: "/images/cookware.jpg",
            subCategories: [
              { name: "Pots & Pans", slug: "pots-pans" },
              { name: "Bakeware", slug: "bakeware" },
              { name: "Cookware Sets", slug: "cookware-sets" },
            ],
          },
          {
            name: "Kitchen Tools & Gadgets",
            slug: "kitchen-tools-gadgets",
            parentCategory: "Kitchen & Dining",
            status: "active",
            sortOrder: 2,
            metaTitle: "Kitchen Tools & Gadgets",
            metaDescription: "Kitchen Tools & Gadgets",
            image: "/images/kitchen-tools-gadgets.jpg",
            subCategories: [
              { name: "Utensils", slug: "utensils" },
              { name: "Knives", slug: "knives" },
              { name: "Measuring Tools", slug: "measuring-tools" },
            ],
          },
          {
            name: "Tableware",
            slug: "tableware",
            parentCategory: "Kitchen & Dining",
            status: "active",
            sortOrder: 3,
            metaTitle: "Tableware",
            metaDescription: "Tableware",
            image: "/images/tableware.jpg",
            subCategories: [
              { name: "Dinnerware", slug: "dinnerware" },
              { name: "Drinkware", slug: "drinkware" },
              { name: "Cutlery", slug: "cutlery" },
            ],
          },
          {
            name: "Small Appliances",
            slug: "small-appliances",
            parentCategory: "Kitchen & Dining",
            status: "active",
            sortOrder: 4,
            metaTitle: "Small Appliances",
            metaDescription: "Small Appliances",
            image: "/images/small-appliances.jpg",
            subCategories: [
              { name: "Coffee Makers", slug: "coffee-makers" },
              { name: "Blenders", slug: "blenders" },
              { name: "Toasters", slug: "toasters" },
            ],
          },
        ],
      },
      {
        name: "Bedding & Bath",
        slug: "bedding-bath",
        parentCategory: "Home & Garden",
        status: "active",
        sortOrder: 4,
        metaTitle: "Bedding & Bath",
        metaDescription: "Bedding & Bath Category",
        image: "/images/bedding-bath.jpg",
        subCategories: [
          {
            name: "Bedding",
            slug: "bedding",
            parentCategory: "Bedding & Bath",
            status: "active",
            sortOrder: 1,
            metaTitle: "Bedding",
            metaDescription: "Bedding",
            image: "/images/bedding.jpg",
            subCategories: [
              { name: "Bed Sheets", slug: "bed-sheets" },
              { name: "Comforters", slug: "comforters" },
              { name: "Pillows", slug: "pillows" },
            ],
          },
          {
            name: "Bath",
            slug: "bath",
            parentCategory: "Bedding & Bath",
            status: "active",
            sortOrder: 2,
            metaTitle: "Bath",
            metaDescription: "Bath",
            image: "/images/bath.jpg",
            subCategories: [
              { name: "Towels", slug: "towels" },
              { name: "Bath Mats", slug: "bath-mats" },
              { name: "Shower Curtains", slug: "shower-curtains" },
            ],
          },
        ],
      },
      {
        name: "Garden & Outdoor",
        slug: "garden-outdoor",
        parentCategory: "Home & Garden",
        status: "active",
        sortOrder: 5,
        metaTitle: "Garden & Outdoor",
        metaDescription: "Garden & Outdoor Category",
        image: "/images/garden-outdoor.jpg",
        subCategories: [
          {
            name: "Outdoor Furniture",
            slug: "outdoor-furniture",
            parentCategory: "Garden & Outdoor",
            status: "active",
            sortOrder: 1,
            metaTitle: "Outdoor Furniture",
            metaDescription: "Outdoor Furniture",
            image: "/images/outdoor-furniture.jpg",
            subCategories: [
              { name: "Patio Sets", slug: "patio-sets" },
              { name: "Garden Benches", slug: "garden-benches" },
              { name: "Hammocks", slug: "hammocks" },
            ],
          },
          {
            name: "Grills & Outdoor Cooking",
            slug: "grills-outdoor-cooking",
            parentCategory: "Garden & Outdoor",
            status: "active",
            sortOrder: 2,
            metaTitle: "Grills & Outdoor Cooking",
            metaDescription: "Grills & Outdoor Cooking",
            image: "/images/grills-outdoor-cooking.jpg",
            subCategories: [
              { name: "Gas Grills", slug: "gas-grills" },
              { name: "Charcoal Grills", slug: "charcoal-grills" },
              { name: "Smokers", slug: "smokers" },
            ],
          },
          {
            name: "Gardening",
            slug: "gardening",
            parentCategory: "Garden & Outdoor",
            status: "active",
            sortOrder: 3,
            metaTitle: "Gardening",
            metaDescription: "Gardening",
            image: "/images/gardening.jpg",
            subCategories: [
              { name: "Garden Tools", slug: "garden-tools" },
              { name: "Plants & Seeds", slug: "plants-seeds" },
              { name: "Planters", slug: "planters" },
            ],
          },
          {
            name: "Outdoor Decor",
            slug: "outdoor-decor",
            parentCategory: "Garden & Outdoor",
            status: "active",
            sortOrder: 4,
            metaTitle: "Outdoor Decor",
            metaDescription: "Outdoor Decor",
            image: "/images/outdoor-decor.jpg",
            subCategories: [
              { name: "Outdoor Lighting", slug: "outdoor-lighting" },
              { name: "Garden Statues", slug: "garden-statues" },
            ],
          },
        ],
      },
      {
        name: "Home Improvement",
        slug: "home-improvement",
        parentCategory: "Home & Garden",
        status: "active",
        sortOrder: 6,
        metaTitle: "Home Improvement",
        metaDescription: "Home Improvement Category",
        image: "/images/home-improvement.jpg",
        subCategories: [
          {
            name: "Lighting",
            slug: "lighting",
            parentCategory: "Home Improvement",
            status: "active",
            sortOrder: 1,
            metaTitle: "Lighting",
            metaDescription: "Lighting",
            image: "/images/lighting.jpg",
            subCategories: [
              { name: "Ceiling Lights", slug: "ceiling-lights" },
              { name: "Table Lamps", slug: "table-lamps" },
              { name: "Wall Lights", slug: "wall-lights" },
            ],
          },
          {
            name: "Hardware",
            slug: "hardware",
            parentCategory: "Home Improvement",
            status: "active",
            sortOrder: 2,
            metaTitle: "Hardware",
            metaDescription: "Hardware",
            image: "/images/hardware.jpg",
            subCategories: [
              { name: "Tools", slug: "tools" },
              { name: "Fasteners", slug: "fasteners" },
              { name: "Locks", slug: "locks" },
            ],
          },
          {
            name: "Paint & Wall Treatments",
            slug: "paint-wall-treatments",
            parentCategory: "Home Improvement",
            status: "active",
            sortOrder: 3,
            metaTitle: "Paint & Wall Treatments",
            metaDescription: "Paint & Wall Treatments",
            image: "/images/paint-wall-treatments.jpg",
          },
          {
            name: "Storage & Organization",
            slug: "storage-organization",
            parentCategory: "Home Improvement",
            status: "active",
            sortOrder: 4,
            metaTitle: "Storage & Organization",
            metaDescription: "Storage & Organization",
            image: "/images/storage-organization.jpg",
            subCategories: [
              { name: "Closet Organizers", slug: "closet-organizers" },
              { name: "Shelving", slug: "shelving" },
              { name: "Storage Bins", slug: "storage-bins" },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Beauty & Personal Care",
    slug: "beauty-personal-care",
    parentCategory: null,
    status: "active",
    sortOrder: 3,
    metaTitle: "Beauty & Personal Care",
    metaDescription: "Beauty & Personal Care Category",
    image: "/images/beauty-personal-care.jpg",
    subCategories: [
      {
        name: "Skincare",
        slug: "skincare",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 1,
        metaTitle: "Skincare",
        metaDescription: "Skincare Category",
        image: "/images/skincare.jpg",
        subCategories: [
          {
            name: "Moisturizers",
            slug: "moisturizers",
            parentCategory: "Skincare",
            status: "active",
            sortOrder: 1,
            metaTitle: "Moisturizers",
            metaDescription: "Moisturizers",
            image: "/images/moisturizers.jpg",
          },
          {
            name: "Cleansers",
            slug: "cleansers",
            parentCategory: "Skincare",
            status: "active",
            sortOrder: 2,
            metaTitle: "Cleansers",
            metaDescription: "Cleansers",
            image: "/images/cleansers.jpg",
          },
          {
            name: "Serums & Treatments",
            slug: "serums-treatments",
            parentCategory: "Skincare",
            status: "active",
            sortOrder: 3,
            metaTitle: "Serums & Treatments",
            metaDescription: "Serums & Treatments",
            image: "/images/serums-treatments.jpg",
          },
          {
            name: "Face Masks",
            slug: "face-masks",
            parentCategory: "Skincare",
            status: "active",
            sortOrder: 4,
            metaTitle: "Face Masks",
            metaDescription: "Face Masks",
            image: "/images/face-masks.jpg",
          },
          {
            name: "Eye Care",
            slug: "eye-care",
            parentCategory: "Skincare",
            status: "active",
            sortOrder: 5,
            metaTitle: "Eye Care",
            metaDescription: "Eye Care",
            image: "/images/eye-care.jpg",
          },
        ],
      },
      {
        name: "Makeup",
        slug: "makeup",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 2,
        metaTitle: "Makeup",
        metaDescription: "Makeup Category",
        image: "/images/makeup.jpg",
        subCategories: [
          {
            name: "Face",
            slug: "face-makeup",
            parentCategory: "Makeup",
            status: "active",
            sortOrder: 1,
            metaTitle: "Face Makeup",
            metaDescription: "Face Makeup",
            image: "/images/face-makeup.jpg",
            subCategories: [
              { name: "Foundation", slug: "foundation" },
              { name: "Concealer", slug: "concealer" },
              { name: "Powder", slug: "powder" },
            ],
          },
          {
            name: "Eyes",
            slug: "eye-makeup",
            parentCategory: "Makeup",
            status: "active",
            sortOrder: 2,
            metaTitle: "Eye Makeup",
            metaDescription: "Eye Makeup",
            image: "/images/eye-makeup.jpg",
            subCategories: [
              { name: "Eyeshadow", slug: "eyeshadow" },
              { name: "Mascara", slug: "mascara" },
              { name: "Eyeliner", slug: "eyeliner" },
            ],
          },
          {
            name: "Lips",
            slug: "lip-makeup",
            parentCategory: "Makeup",
            status: "active",
            sortOrder: 3,
            metaTitle: "Lip Makeup",
            metaDescription: "Lip Makeup",
            image: "/images/lip-makeup.jpg",
            subCategories: [
              { name: "Lipstick", slug: "lipstick" },
              { name: "Lip Gloss", slug: "lip-gloss" },
              { name: "Lip Liner", slug: "lip-liner" },
            ],
          },
          {
            name: "Makeup Sets",
            slug: "makeup-sets",
            parentCategory: "Makeup",
            status: "active",
            sortOrder: 4,
            metaTitle: "Makeup Sets",
            metaDescription: "Makeup Sets",
            image: "/images/makeup-sets.jpg",
          },
        ],
      },
      {
        name: "Hair Care",
        slug: "hair-care",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 3,
        metaTitle: "Hair Care",
        metaDescription: "Hair Care Category",
        image: "/images/hair-care.jpg",
        subCategories: [
          {
            name: "Shampoo & Conditioner",
            slug: "shampoo-conditioner",
            parentCategory: "Hair Care",
            status: "active",
            sortOrder: 1,
            metaTitle: "Shampoo & Conditioner",
            metaDescription: "Shampoo & Conditioner",
            image: "/images/shampoo-conditioner.jpg",
          },
          {
            name: "Hair Treatments",
            slug: "hair-treatments",
            parentCategory: "Hair Care",
            status: "active",
            sortOrder: 2,
            metaTitle: "Hair Treatments",
            metaDescription: "Hair Treatments",
            image: "/images/hair-treatments.jpg",
          },
          {
            name: "Hair Styling",
            slug: "hair-styling",
            parentCategory: "Hair Care",
            status: "active",
            sortOrder: 3,
            metaTitle: "Hair Styling",
            metaDescription: "Hair Styling",
            image: "/images/hair-styling.jpg",
          },
          {
            name: "Hair Color",
            slug: "hair-color",
            parentCategory: "Hair Care",
            status: "active",
            sortOrder: 4,
            metaTitle: "Hair Color",
            metaDescription: "Hair Color",
            image: "/images/hair-color.jpg",
          },
        ],
      },
      {
        name: "Fragrances",
        slug: "fragrances",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 4,
        metaTitle: "Fragrances",
        metaDescription: "Fragrances Category",
        image: "/images/fragrances.jpg",
        subCategories: [
          {
            name: "Women's Perfume",
            slug: "womens-perfume",
            parentCategory: "Fragrances",
            status: "active",
            sortOrder: 1,
            metaTitle: "Women's Perfume",
            metaDescription: "Women's Perfume",
            image: "/images/womens-perfume.jpg",
          },
          {
            name: "Men's Cologne",
            slug: "mens-cologne",
            parentCategory: "Fragrances",
            status: "active",
            sortOrder: 2,
            metaTitle: "Men's Cologne",
            metaDescription: "Men's Cologne",
            image: "/images/mens-cologne.jpg",
          },
          {
            name: "Unisex Fragrances",
            slug: "unisex-fragrances",
            parentCategory: "Fragrances",
            status: "active",
            sortOrder: 3,
            metaTitle: "Unisex Fragrances",
            metaDescription: "Unisex Fragrances",
            image: "/images/unisex-fragrances.jpg",
          },
        ],
      },
      {
        name: "Bath & Body",
        slug: "bath-body",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 5,
        metaTitle: "Bath & Body",
        metaDescription: "Bath & Body Category",
        image: "/images/bath-body.jpg",
        subCategories: [
          {
            name: "Body Wash & Shower Gel",
            slug: "body-wash-shower-gel",
            parentCategory: "Bath & Body",
            status: "active",
            sortOrder: 1,
            metaTitle: "Body Wash & Shower Gel",
            metaDescription: "Body Wash & Shower Gel",
            image: "/images/body-wash-shower-gel.jpg",
          },
          {
            name: "Body Lotion",
            slug: "body-lotion",
            parentCategory: "Bath & Body",
            status: "active",
            sortOrder: 2,
            metaTitle: "Body Lotion",
            metaDescription: "Body Lotion",
            image: "/images/body-lotion.jpg",
          },
          {
            name: "Deodorant",
            slug: "deodorant",
            parentCategory: "Bath & Body",
            status: "active",
            sortOrder: 3,
            metaTitle: "Deodorant",
            metaDescription: "Deodorant",
            image: "/images/deodorant.jpg",
          },
          {
            name: "Hand Care",
            slug: "hand-care",
            parentCategory: "Bath & Body",
            status: "active",
            sortOrder: 4,
            metaTitle: "Hand Care",
            metaDescription: "Hand Care",
            image: "/images/hand-care.jpg",
          },
        ],
      },
      {
        name: "Men's Grooming",
        slug: "mens-grooming",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 6,
        metaTitle: "Men's Grooming",
        metaDescription: "Men's Grooming Category",
        image: "/images/mens-grooming.jpg",
        subCategories: [
          {
            name: "Shaving",
            slug: "shaving",
            parentCategory: "Men's Grooming",
            status: "active",
            sortOrder: 1,
            metaTitle: "Shaving",
            metaDescription: "Shaving",
            image: "/images/shaving.jpg",
            subCategories: [
              { name: "Razors", slug: "razors" },
              { name: "Shaving Cream", slug: "shaving-cream" },
              { name: "Aftershave", slug: "aftershave" },
            ],
          },
          {
            name: "Beard Care",
            slug: "beard-care",
            parentCategory: "Men's Grooming",
            status: "active",
            sortOrder: 2,
            metaTitle: "Beard Care",
            metaDescription: "Beard Care",
            image: "/images/beard-care.jpg",
          },
          {
            name: "Men's Skincare",
            slug: "mens-skincare",
            parentCategory: "Men's Grooming",
            status: "active",
            sortOrder: 3,
            metaTitle: "Men's Skincare",
            metaDescription: "Men's Skincare",
            image: "/images/mens-skincare.jpg",
          },
        ],
      },
      {
        name: "Personal Care",
        slug: "personal-care",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 7,
        metaTitle: "Personal Care",
        metaDescription: "Personal Care Category",
        image: "/images/personal-care.jpg",
        subCategories: [
          {
            name: "Oral Care",
            slug: "oral-care",
            parentCategory: "Personal Care",
            status: "active",
            sortOrder: 1,
            metaTitle: "Oral Care",
            metaDescription: "Oral Care",
            image: "/images/oral-care.jpg",
          },
          {
            name: "Feminine Care",
            slug: "feminine-care",
            parentCategory: "Personal Care",
            status: "active",
            sortOrder: 2,
            metaTitle: "Feminine Care",
            metaDescription: "Feminine Care",
            image: "/images/feminine-care.jpg",
          },
          {
            name: "Hair Removal",
            slug: "hair-removal",
            parentCategory: "Personal Care",
            status: "active",
            sortOrder: 3,
            metaTitle: "Hair Removal",
            metaDescription: "Hair Removal",
            image: "/images/hair-removal.jpg",
          },
        ],
      },
    ],
  },
  {
    name: "Toys & Games",
    slug: "toys-games",
    parentCategory: null,
    status: "active",
    sortOrder: 4,
    metaTitle: "Toys & Games",
    metaDescription: "Toys & Games Category",
    image: "/images/toys-games.jpg",
    subCategories: [
      {
        name: "Toys for Kids",
        slug: "toys-for-kids",
        parentCategory: "Toys & Games",
        status: "active",
        sortOrder: 1,
        metaTitle: "Toys for Kids",
        metaDescription: "Toys for Kids Category",
        image: "/images/toys-for-kids.jpg",
        subCategories: [
          {
            name: "Action Figures",
            slug: "action-figures",
            parentCategory: "Toys for Kids",
            status: "active",
            sortOrder: 1,
            metaTitle: "Action Figures",
            metaDescription: "Action Figures",
            image: "/images/action-figures.jpg",
          },
          {
            name: "Dolls & Accessories",
            slug: "dolls-accessories",
            parentCategory: "Toys for Kids",
            status: "active",
            sortOrder: 2,
            metaTitle: "Dolls & Accessories",
            metaDescription: "Dolls & Accessories",
            image: "/images/dolls-accessories.jpg",
          },
          {
            name: "Building Toys",
            slug: "building-toys",
            parentCategory: "Toys for Kids",
            status: "active",
            sortOrder: 3,
            metaTitle: "Building Toys",
            metaDescription: "Building Toys",
            image: "/images/building-toys.jpg",
            subCategories: [
              { name: "LEGO", slug: "lego" },
              { name: "Building Blocks", slug: "building-blocks" },
            ],
          },
          {
            name: "Plush Toys",
            slug: "plush-toys",
            parentCategory: "Toys for Kids",
            status: "active",
            sortOrder: 4,
            metaTitle: "Plush Toys",
            metaDescription: "Plush Toys",
            image: "/images/plush-toys.jpg",
          },
        ],
      },
      {
        name: "Games",
        slug: "games",
        parentCategory: "Toys & Games",
        status: "active",
        sortOrder: 2,
        metaTitle: "Games",
        metaDescription: "Games Category",
        image: "/images/games.jpg",
        subCategories: [
          {
            name: "Board Games",
            slug: "board-games",
            parentCategory: "Games",
            status: "active",
            sortOrder: 1,
            metaTitle: "Board Games",
            metaDescription: "Board Games",
            image: "/images/board-games.jpg",
          },
          {
            name: "Card Games",
            slug: "card-games",
            parentCategory: "Games",
            status: "active",
            sortOrder: 2,
            metaTitle: "Card Games",
            metaDescription: "Card Games",
            image: "/images/card-games.jpg",
          },
          {
            name: "Puzzles",
            slug: "puzzles",
            parentCategory: "Games",
            status: "active",
            sortOrder: 3,
            metaTitle: "Puzzles",
            metaDescription: "Puzzles",
            image: "/images/puzzles.jpg",
            subCategories: [
              { name: "Jigsaw Puzzles", slug: "jigsaw-puzzles" },
              { name: "3D Puzzles", slug: "3d-puzzles" },
            ],
          },
        ],
      },
      {
        name: "Outdoor Toys",
        slug: "outdoor-toys",
        parentCategory: "Toys & Games",
        status: "active",
        sortOrder: 3,
        metaTitle: "Outdoor Toys",
        metaDescription: "Outdoor Toys",
        image: "/images/outdoor-toys.jpg",
        subCategories: [
          {
            name: "Playhouses",
            slug: "playhouses",
            parentCategory: "Outdoor Toys",
            status: "active",
            sortOrder: 1,
            metaTitle: "Playhouses",
            metaDescription: "Playhouses",
            image: "/images/playhouses.jpg",
          },
          {
            name: "Swing Sets",
            slug: "swing-sets",
            parentCategory: "Outdoor Toys",
            status: "active",
            sortOrder: 2,
            metaTitle: "Swing Sets",
            metaDescription: "Swing Sets",
            image: "/images/swing-sets.jpg",
          },
          {
            name: "Trampolines",
            slug: "trampolines",
            parentCategory: "Outdoor Toys",
            status: "active",
            sortOrder: 3,
            metaTitle: "Trampolines",
            metaDescription: "Trampolines",
            image: "/images/trampolines.jpg",
          },
        ],
      },
      {
        name: "Learning & Education",
        slug: "learning-education",
        parentCategory: "Toys & Games",
        status: "active",
        sortOrder: 4,
        metaTitle: "Learning & Education",
        metaDescription: "Learning & Education",
        image: "/images/learning-education.jpg",
        subCategories: [
          {
            name: "Science Kits",
            slug: "science-kits",
            parentCategory: "Learning & Education",
            status: "active",
            sortOrder: 1,
            metaTitle: "Science Kits",
            metaDescription: "Science Kits",
            image: "/images/science-kits.jpg",
          },
          {
            name: "STEM Toys",
            slug: "stem-toys",
            parentCategory: "Learning & Education",
            status: "active",
            sortOrder: 2,
            metaTitle: "STEM Toys",
            metaDescription: "STEM Toys",
            image: "/images/stem-toys.jpg",
          },
          {
            name: "Art & Craft Kits",
            slug: "art-craft-kits",
            parentCategory: "Learning & Education",
            status: "active",
            sortOrder: 3,
            metaTitle: "Art & Craft Kits",
            metaDescription: "Art & Craft Kits",
            image: "/images/art-craft-kits.jpg",
          },
        ],
      },
      {
        name: "Video Games",
        slug: "video-games",
        parentCategory: "Toys & Games",
        status: "active",
        sortOrder: 5,
        metaTitle: "Video Games",
        metaDescription: "Video Games",
        image: "/images/video-games.jpg",
        subCategories: [
          {
            name: "Console Games",
            slug: "console-games",
            parentCategory: "Video Games",
            status: "active",
            sortOrder: 1,
            metaTitle: "Console Games",
            metaDescription: "Console Games",
            image: "/images/console-games.jpg",
          },
          {
            name: "PC Games",
            slug: "pc-games",
            parentCategory: "Video Games",
            status: "active",
            sortOrder: 2,
            metaTitle: "PC Games",
            metaDescription: "PC Games",
            image: "/images/pc-games.jpg",
          },
          {
            name: "Gaming Accessories",
            slug: "gaming-accessories",
            parentCategory: "Video Games",
            status: "active",
            sortOrder: 3,
            metaTitle: "Gaming Accessories",
            metaDescription: "Gaming Accessories",
            image: "/images/gaming-accessories.jpg",
          },
        ],
      },
    ],
  },
  {
    name: "Luxury Goods",
    slug: "luxury-goods",
    parentCategory: null,
    status: "active",
    sortOrder: 5,
    metaTitle: "Luxury Goods",
    metaDescription: "Luxury Goods Category",
    image: "/images/luxury-goods.jpg",
    subCategories: [
      {
        name: "Luxury Watches",
        slug: "luxury-watches",
        parentCategory: "Luxury Goods",
        status: "active",
        sortOrder: 1,
        metaTitle: "Luxury Watches",
        metaDescription: "Luxury Watches",
        image: "/images/luxury-watches.jpg",
        subCategories: [
          {
            name: "Men's Luxury Watches",
            slug: "mens-luxury-watches",
            parentCategory: "Luxury Watches",
            status: "active",
            sortOrder: 1,
            metaTitle: "Men's Luxury Watches",
            metaDescription: "Men's Luxury Watches",
            image: "/images/mens-luxury-watches.jpg",
          },
          {
            name: "Women's Luxury Watches",
            slug: "womens-luxury-watches",
            parentCategory: "Luxury Watches",
            status: "active",
            sortOrder: 2,
            metaTitle: "Women's Luxury Watches",
            metaDescription: "Women's Luxury Watches",
            image: "/images/womens-luxury-watches.jpg",
          },
        ],
      },
      {
        name: "Designer Handbags",
        slug: "designer-handbags",
        parentCategory: "Luxury Goods",
        status: "active",
        sortOrder: 2,
        metaTitle: "Designer Handbags",
        metaDescription: "Designer Handbags",
        image: "/images/designer-handbags.jpg",
        subCategories: [
          {
            name: "Shoulder Bags",
            slug: "shoulder-bags",
            parentCategory: "Designer Handbags",
            status: "active",
            sortOrder: 1,
            metaTitle: "Shoulder Bags",
            metaDescription: "Shoulder Bags",
            image: "/images/shoulder-bags.jpg",
          },
          {
            name: "Tote Bags",
            slug: "tote-bags",
            parentCategory: "Designer Handbags",
            status: "active",
            sortOrder: 2,
            metaTitle: "Tote Bags",
            metaDescription: "Tote Bags",
            image: "/images/tote-bags.jpg",
          },
          {
            name: "Clutches",
            slug: "clutches",
            parentCategory: "Designer Handbags",
            status: "active",
            sortOrder: 3,
            metaTitle: "Clutches",
            metaDescription: "Clutches",
            image: "/images/clutches.jpg",
          },
        ],
      },
      {
        name: "Fine Jewelry",
        slug: "fine-jewelry",
        parentCategory: "Luxury Goods",
        status: "active",
        sortOrder: 3,
        metaTitle: "Fine Jewelry",
        metaDescription: "Fine Jewelry",
        image: "/images/fine-jewelry.jpg",
        subCategories: [
          {
            name: "Rings",
            slug: "fine-jewelry-rings",
            parentCategory: "Fine Jewelry",
            status: "active",
            sortOrder: 1,
            metaTitle: "Fine Jewelry Rings",
            metaDescription: "Fine Jewelry Rings",
            image: "/images/fine-jewelry-rings.jpg",
          },
          {
            name: "Necklaces",
            slug: "fine-jewelry-necklaces",
            parentCategory: "Fine Jewelry",
            status: "active",
            sortOrder: 2,
            metaTitle: "Fine Jewelry Necklaces",
            metaDescription: "Fine Jewelry Necklaces",
            image: "/images/fine-jewelry-necklaces.jpg",
          },
          {
            name: "Bracelets",
            slug: "fine-jewelry-bracelets",
            parentCategory: "Fine Jewelry",
            status: "active",
            sortOrder: 3,
            metaTitle: "Fine Jewelry Bracelets",
            metaDescription: "Fine Jewelry Bracelets",
            image: "/images/fine-jewelry-bracelets.jpg",
          },
          {
            name: "Earrings",
            slug: "fine-jewelry-earrings",
            parentCategory: "Fine Jewelry",
            status: "active",
            sortOrder: 4,
            metaTitle: "Fine Jewelry Earrings",
            metaDescription: "Fine Jewelry Earrings",
            image: "/images/fine-jewelry-earrings.jpg",
          },
        ],
      },
    ],
  },
  {
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    parentCategory: null,
    status: "active",
    sortOrder: 6,
    metaTitle: "Sports & Outdoors",
    metaDescription: "Sports & Outdoors Category",
    image: "/images/sports-outdoors.jpg",
    subCategories: [
      {
        name: "Fitness Equipment",
        slug: "fitness-equipment",
        parentCategory: "Sports & Outdoors",
        status: "active",
        sortOrder: 1,
        metaTitle: "Fitness Equipment",
        metaDescription: "Fitness Equipment Category",
        image: "/images/fitness-equipment.jpg",
        subCategories: [
          {
            name: "Cardio Machines",
            slug: "cardio-machines",
            parentCategory: "Fitness Equipment",
            status: "active",
            sortOrder: 1,
            metaTitle: "Cardio Machines",
            metaDescription: "Cardio Machines",
            image: "/images/cardio-machines.jpg",
          },
          {
            name: "Strength Training Equipment",
            slug: "strength-training-equipment",
            parentCategory: "Fitness Equipment",
            status: "active",
            sortOrder: 2,
            metaTitle: "Strength Training Equipment",
            metaDescription: "Strength Training Equipment",
            image: "/images/strength-training-equipment.jpg",
          },
          {
            name: "Yoga & Pilates Gear",
            slug: "yoga-pilates-gear",
            parentCategory: "Fitness Equipment",
            status: "active",
            sortOrder: 3,
            metaTitle: "Yoga & Pilates Gear",
            metaDescription: "Yoga & Pilates Gear",
            image: "/images/yoga-pilates-gear.jpg",
          },
        ],
      },
      {
        name: "Outdoor Recreation",
        slug: "outdoor-recreation",
        parentCategory: "Sports & Outdoors",
        status: "active",
        sortOrder: 2,
        metaTitle: "Outdoor Recreation Category",
        metaDescription: "Outdoor Recreation Category Description.",
        image: "/images/outdoor-recreation.jpg",
      },
      {
        name: "Camping & Hiking",
        slug: "camping-hiking",
        parentCategory: "Sports & Outdoors",
        status: "active",
        sortOrder: "3",
        metaTitle: "Camping & Hiking",
        metaDescription: "Camping & Hiking Category",
        image: "/images/camping-hiking.jpg",
        subCategories: [
          {
            name: "Tents",
            slug: "tents",
            parentCategory: "Camping & Hiking",
            status: "active",
            sortOrder: 1,
            metaTitle: "Tents",
            metaDescription: "Tents Category",
            image: "/images/tents.jpg",
          },
          {
            name: "Sleeping Bags",
            slug: "sleeping-bags",
            parentCategory: "Camping & Hiking",
            status: "active",
            sortOrder: 2,
            metaTitle: "Sleeping Bags",
            metaDescription: "Sleeping Bags Category",
            image: "/images/sleeping-bags.jpg",
          },
          {
            name: "Backpacks",
            slug: "backpacks",
            parentCategory: "Camping & Hiking",
            status: "active",
            sortOrder: 3,
            metaTitle: "Backpacks",
            metaDescription: "Backpacks Category",
            image: "/images/backpacks.jpg",
          },
        ],
      },
    ],
  },
  {
    name: "Grocery & Gourmet Food",
    slug: "grocery-gourmet-food",
    parentCategory: null,
    status: "active",
    sortOrder: 11,
    metaTitle: "Grocery & Gourmet Food",
    metaDescription: "Grocery & Gourmet Food Category",
    image: "/images/grocery-gourmet-food.jpg",
    subCategories: [
      {
        name: "Fresh Produce",
        slug: "fresh-produce",
        parentCategory: "Grocery & Gourmet Food",
        status: "active",
        sortOrder: 1,
        metaTitle: "Fresh Produce",
        metaDescription: "Fresh Produce",
        image: "/images/fresh-produce.jpg",
        subCategories: [
          { name: "Fruits", slug: "fruits" },
          { name: "Vegetables", slug: "vegetables" },
          { name: "Herbs", slug: "herbs" },
        ],
      },
      {
        name: "Snacks",
        slug: "snacks",
        parentCategory: "Grocery & Gourmet Food",
        status: "active",
        sortOrder: 2,
        metaTitle: "Snacks",
        metaDescription: "Snacks",
        image: "/images/snacks.jpg",
        subCategories: [
          { name: "Chips & Crisps", slug: "chips-crisps" },
          { name: "Nuts & Seeds", slug: "nuts-seeds" },
          { name: "Chocolate & Candy", slug: "chocolate-candy" },
        ],
      },
      {
        name: "Beverages",
        slug: "beverages",
        parentCategory: "Grocery & Gourmet Food",
        status: "active",
        sortOrder: 3,
        metaTitle: "Beverages",
        metaDescription: "Beverages",
        image: "/images/beverages.jpg",
        subCategories: [
          { name: "Coffee", slug: "coffee" },
          { name: "Tea", slug: "tea" },
          { name: "Juices", slug: "juices" },
          { name: "Soft Drinks", slug: "soft-drinks" },
        ],
      },
    ],
  },
  {
    name: "Industrial & Scientific",
    slug: "industrial-scientific",
    parentCategory: null,
    status: "active",
    sortOrder: 12,
    metaTitle: "Industrial & Scientific",
    metaDescription: "Industrial & Scientific Category",
    image: "/images/industrial-scientific.jpg",
    subCategories: [
      {
        name: "Lab Supplies",
        slug: "lab-supplies",
        parentCategory: "Industrial & Scientific",
        status: "active",
        sortOrder: 1,
        metaTitle: "Lab Supplies",
        metaDescription: "Lab Supplies",
        image: "/images/lab-supplies.jpg",
        subCategories: [
          { name: "Microscopes", slug: "microscopes" },
          { name: "Beakers & Flasks", slug: "beakers-flasks" },
          { name: "Lab Safety Equipment", slug: "lab-safety-equipment" },
        ],
      },
      {
        name: "Industrial Hardware",
        slug: "industrial-hardware",
        parentCategory: "Industrial & Scientific",
        status: "active",
        sortOrder: 2,
        metaTitle: "Industrial Hardware",
        metaDescription: "Industrial Hardware",
        image: "/images/industrial-hardware.jpg",
        subCategories: [
          { name: "Fasteners", slug: "industrial-fasteners" },
          { name: "Bearings", slug: "bearings" },
          { name: "Valves", slug: "valves" },
        ],
      },
    ],
  },
  {
    name: "Arts, Crafts & Sewing",
    slug: "arts-crafts-sewing",
    parentCategory: null,
    status: "active",
    sortOrder: 13,
    metaTitle: "Arts, Crafts & Sewing",
    metaDescription: "Arts, Crafts & Sewing Category",
    image: "/images/arts-crafts-sewing.jpg",
    subCategories: [
      {
        name: "Drawing & Painting",
        slug: "drawing-painting",
        parentCategory: "Arts, Crafts & Sewing",
        status: "active",
        sortOrder: 1,
        metaTitle: "Drawing & Painting",
        metaDescription: "Drawing & Painting",
        image: "/images/drawing-painting.jpg",
        subCategories: [
          { name: "Paints", slug: "paints" },
          { name: "Brushes", slug: "brushes" },
          { name: "Canvases", slug: "canvases" },
        ],
      },
      {
        name: "Sewing",
        slug: "sewing",
        parentCategory: "Arts, Crafts & Sewing",
        status: "active",
        sortOrder: 2,
        metaTitle: "Sewing",
        metaDescription: "Sewing",
        image: "/images/sewing.jpg",
        subCategories: [
          { name: "Sewing Machines", slug: "sewing-machines" },
          { name: "Fabric", slug: "fabric" },
          { name: "Patterns", slug: "sewing-patterns" },
        ],
      },
    ],
  },
  {
    name: "Musical Instruments",
    slug: "musical-instruments",
    parentCategory: null,
    status: "active",
    sortOrder: 14,
    metaTitle: "Musical Instruments",
    metaDescription: "Musical Instruments Category",
    image: "/images/musical-instruments.jpg",
    subCategories: [
      {
        name: "Guitars",
        slug: "guitars",
        parentCategory: "Musical Instruments",
        status: "active",
        sortOrder: 1,
        metaTitle: "Guitars",
        metaDescription: "Guitars",
        image: "/images/guitars.jpg",
        subCategories: [
          { name: "Acoustic Guitars", slug: "acoustic-guitars" },
          { name: "Electric Guitars", slug: "electric-guitars" },
          { name: "Bass Guitars", slug: "bass-guitars" },
        ],
      },
      {
        name: "Keyboards",
        slug: "keyboards",
        parentCategory: "Musical Instruments",
        status: "active",
        sortOrder: 2,
        metaTitle: "Keyboards",
        metaDescription: "Keyboards",
        image: "/images/keyboards.jpg",
        subCategories: [
          { name: "Digital Pianos", slug: "digital-pianos" },
          { name: "Synthesizers", slug: "synthesizers" },
          { name: "MIDI Controllers", slug: "midi-controllers" },
        ],
      },
    ],
  },
  {
    name: "Software",
    slug: "software",
    parentCategory: null,
    status: "active",
    sortOrder: 15,
    metaTitle: "Software",
    metaDescription: "Software Category",
    image: "/images/software.jpg",
    subCategories: [
      {
        name: "Business Software",
        slug: "business-software",
        parentCategory: "Software",
        status: "active",
        sortOrder: 1,
        metaTitle: "Business Software",
        metaDescription: "Business Software",
        image: "/images/business-software.jpg",
        subCategories: [
          { name: "Accounting", slug: "accounting-software" },
          { name: "Project Management", slug: "project-management-software" },
          { name: "CRM", slug: "crm-software" },
        ],
      },
      {
        name: "Creative Software",
        slug: "creative-software",
        parentCategory: "Software",
        status: "active",
        sortOrder: 2,
        metaTitle: "Creative Software",
        metaDescription: "Creative Software",
        image: "/images/creative-software.jpg",
        subCategories: [
          { name: "Photo Editing", slug: "photo-editing-software" },
          { name: "Video Editing", slug: "video-editing-software" },
          { name: "3D Modeling", slug: "3d-modeling-software" },
        ],
      },
    ],
  },
];
