export const defaultCategories = [
  {
    name: "Clothing & Apparel",
    slug: "clothing-apparel",
    parentCategory: null,
    status: "active",
    sortOrder: 0,
    metaTitle: "Clothing & Apparel",
    metaDescription: "Clothing & Apparel Category",
    image: "/images/clothing-apparel.jpg",
    subCategories: [
      {
        name: "Men's Clothing",
        slug: "mens-clothing",
        parentCategory: "Clothing & Apparel",
        status: "active",
        sortOrder: 1,
        metaTitle: "Men's Clothing",
        metaDescription: "Men's Clothing Category",
        image: "/images/mens-clothing.jpg",
        subCategories: [
          {
            name: "Shirts",
            slug: "mens-shirts",
            parentCategory: "Men's Clothing",
            status: "active",
            sortOrder: 1,
            metaTitle: "Shirts",
            metaDescription: "Men's Shirts",
            image: "/images/mens-shirts.jpg",
          },
          {
            name: "Trousers",
            slug: "mens-trousers",
            parentCategory: "Men's Clothing",
            status: "active",
            sortOrder: 2,
            metaTitle: "Trousers",
            metaDescription: "Men's Trousers",
            image: "/images/mens-trousers.jpg",
          },
        ],
      },
      {
        name: "Women's Clothing",
        slug: "womens-clothing",
        parentCategory: "Clothing & Apparel",
        status: "active",
        sortOrder: 2,
        metaTitle: "Women's Clothing",
        metaDescription: "Women's Clothing Category",
        image: "/images/womens-clothing.jpg",
        subCategories: [
          {
            name: "Dresses",
            slug: "womens-dresses",
            parentCategory: "Women's Clothing",
            status: "active",
            sortOrder: 1,
            metaTitle: "Dresses",
            metaDescription: "Women's Dresses",
            image: "/images/womens-dresses.jpg",
          },
          {
            name: "Tops",
            slug: "womens-tops",
            parentCategory: "Women's Clothing",
            status: "active",
            sortOrder: 2,
            metaTitle: "Tops",
            metaDescription: "Women's Tops",
            image: "/images/womens-tops.jpg",
          },
        ],
      },
      {
        name: "Kids' Clothing",
        slug: "kids-clothing",
        parentCategory: "Clothing & Apparel",
        status: "active",
        sortOrder: 3,
        metaTitle: "Kids' Clothing",
        metaDescription: "Kids' Clothing Category",
        image: "/images/kids-clothing.jpg",
        subCategories: [
          {
            name: "Boys' Clothing",
            slug: "boys-clothing",
            parentCategory: "Kids' Clothing",
            status: "active",
            sortOrder: 1,
            metaTitle: "Boys' Clothing",
            metaDescription: "Boys' Clothing",
            image: "/images/boys-clothing.jpg",
          },
          {
            name: "Girls' Clothing",
            slug: "girls-clothing",
            parentCategory: "Kids' Clothing",
            status: "active",
            sortOrder: 2,
            metaTitle: "Girls' Clothing",
            metaDescription: "Girls' Clothing",
            image: "/images/girls-clothing.jpg",
          },
        ],
      },
    ],
  },
  {
    name: "Electronics",
    slug: "electronics",
    parentCategory: null,
    status: "active",
    sortOrder: 1,
    metaTitle: "Electronics",
    metaDescription: "Electronics Category",
    image: "/images/electronics.jpg",
    subCategories: [
      {
        name: "Computers & Laptops",
        slug: "computers-laptops",
        parentCategory: "Electronics",
        status: "active",
        sortOrder: 1,
        metaTitle: "Computers & Laptops",
        metaDescription: "Computers & Laptops Category",
        image: "/images/computers-laptops.jpg",
        subCategories: [
          {
            name: "Laptops",
            slug: "laptops",
            parentCategory: "Computers & Laptops",
            status: "active",
            sortOrder: 1,
            metaTitle: "Laptops",
            metaDescription: "Laptops",
            image: "/images/laptops.jpg",
          },
          {
            name: "Desktops",
            slug: "desktops",
            parentCategory: "Computers & Laptops",
            status: "active",
            sortOrder: 2,
            metaTitle: "Desktops",
            metaDescription: "Desktops",
            image: "/images/desktops.jpg",
          },
        ],
      },
      {
        name: "Smartphones & Accessories",
        slug: "smartphones-accessories",
        parentCategory: "Electronics",
        status: "active",
        sortOrder: 2,
        metaTitle: "Smartphones & Accessories",
        metaDescription: "Smartphones & Accessories Category",
        image: "/images/smartphones-accessories.jpg",
        subCategories: [
          {
            name: "Smartphones",
            slug: "smartphones",
            parentCategory: "Smartphones & Accessories",
            status: "active",
            sortOrder: 1,
            metaTitle: "Smartphones",
            metaDescription: "Smartphones",
            image: "/images/smartphones.jpg",
          },
          {
            name: "Phone Cases",
            slug: "phone-cases",
            parentCategory: "Smartphones & Accessories",
            status: "active",
            sortOrder: 2,
            metaTitle: "Phone Cases",
            metaDescription: "Phone Cases",
            image: "/images/phone-cases.jpg",
          },
        ],
      },
      {
        name: "TVs & Home Theater",
        slug: "tvs-home-theater",
        parentCategory: "Electronics",
        status: "active",
        sortOrder: 3,
        metaTitle: "TVs & Home Theater",
        metaDescription: "TVs & Home Theater Category",
        image: "/images/tvs-home-theater.jpg",
        subCategories: [
          {
            name: "LED TVs",
            slug: "led-tvs",
            parentCategory: "TVs & Home Theater",
            status: "active",
            sortOrder: 1,
            metaTitle: "LED TVs",
            metaDescription: "LED TVs",
            image: "/images/led-tvs.jpg",
          },
          {
            name: "Projectors",
            slug: "projectors",
            parentCategory: "TVs & Home Theater",
            status: "active",
            sortOrder: 2,
            metaTitle: "Projectors",
            metaDescription: "Projectors",
            image: "/images/projectors.jpg",
          },
        ],
      },
    ],
  },
  {
    name: "Home & Garden",
    slug: "home-garden",
    parentCategory: null,
    status: "active",
    sortOrder: 2,
    metaTitle: "Home & Garden",
    metaDescription: "Home & Garden Category",
    image: "/images/home-garden.jpg",
    subCategories: [
      {
        name: "Furniture",
        slug: "furniture",
        parentCategory: "Home & Garden",
        status: "active",
        sortOrder: 1,
        metaTitle: "Furniture",
        metaDescription: "Furniture Category",
        image: "/images/furniture.jpg",
        subCategories: [
          {
            name: "Sofas",
            slug: "sofas",
            parentCategory: "Furniture",
            status: "active",
            sortOrder: 1,
            metaTitle: "Sofas",
            metaDescription: "Sofas",
            image: "/images/sofas.jpg",
          },
          {
            name: "Beds",
            slug: "beds",
            parentCategory: "Furniture",
            status: "active",
            sortOrder: 2,
            metaTitle: "Beds",
            metaDescription: "Beds",
            image: "/images/beds.jpg",
          },
        ],
      },
      {
        name: "Home Decor",
        slug: "home-decor",
        parentCategory: "Home & Garden",
        status: "active",
        sortOrder: 2,
        metaTitle: "Home Decor",
        metaDescription: "Home Decor Category",
        image: "/images/home-decor.jpg",
        subCategories: [
          {
            name: "Wall Art",
            slug: "wall-art",
            parentCategory: "Home Decor",
            status: "active",
            sortOrder: 1,
            metaTitle: "Wall Art",
            metaDescription: "Wall Art",
            image: "/images/wall-art.jpg",
          },
          {
            name: "Clocks",
            slug: "clocks",
            parentCategory: "Home Decor",
            status: "active",
            sortOrder: 2,
            metaTitle: "Clocks",
            metaDescription: "Clocks",
            image: "/images/clocks.jpg",
          },
        ],
      },
    ],
  },

  {
    name: "Beauty & Personal Care",
    slug: "beauty-personal-care",
    parentCategory: null,
    status: "active",
    sortOrder: 3,
    metaTitle: "Beauty & Personal Care",
    metaDescription: "Beauty & Personal Care Category",
    image: "/images/beauty-personal-care.jpg",
    subCategories: [
      {
        name: "Skincare",
        slug: "skincare",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 1,
        metaTitle: "Skincare",
        metaDescription: "Skincare Category",
        image: "/images/skincare.jpg",
      },
      {
        name: "Makeup",
        slug: "makeup",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 2,
        metaTitle: "Makeup",
        metaDescription: "Makeup Category",
        image: "/images/makeup.jpg",
      },
      {
        name: "Hair Care",
        slug: "hair-care",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 3,
        metaTitle: "Hair Care",
        metaDescription: "Hair Care Category",
        image: "/images/hair-care.jpg",
      },
      {
        name: "Fragrances",
        slug: "fragrances",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 4,
        metaTitle: "Fragrances",
        metaDescription: "Fragrances Category",
        image: "/images/fragrances.jpg",
      },
      {
        name: "Bath & Body",
        slug: "bath-body",
        parentCategory: "Beauty & Personal Care",
        status: "active",
        sortOrder: 5,
        metaTitle: "Bath & Body",
        metaDescription: "Bath & Body Category",
        image: "/images/bath-body.jpg",
      },
    ],
  },
  {
    name: "Toys & Games",
    slug: "toys-games",
    parentCategory: null,
    status: "active",
    sortOrder: 4,
    metaTitle: "Toys & Games",
    metaDescription: "Toys & Games Category",
    image: "/images/toys-games.jpg",
    subCategories: [
      {
        name: "Toys for Kids",
        slug: "toys-for-kids",
        parentCategory: "Toys & Games",
        status: "active",
        sortOrder: 1,
        metaTitle: "Toys for Kids",
        metaDescription: "Toys for Kids Category",
        image: "/images/toys-for-kids.jpg",
      },
      {
        name: "Games",
        slug: "games",
        parentCategory: "Toys & Games",
        status: "active",
        sortOrder: 2,
        metaTitle: "Games",
        metaDescription: "Games Category",
        image: "/images/games.jpg",
      },
      {
        name: "Puzzles",
        slug: "puzzles",
        parentCategory: "Toys & Games",
        status: "active",
        sortOrder: 3,
        metaTitle: "Puzzles",
        metaDescription: "Puzzles Category",
        image: "/images/puzzles.jpg",
      },
      {
        name: "Dolls & Action Figures",
        slug: "dolls-action-figures",
        parentCategory: "Toys & Games",
        status: "active",
        sortOrder: 4,
        metaTitle: "Dolls & Action Figures",
        metaDescription: "Dolls & Action Figures Category",
        image: "/images/dolls-action-figures.jpg",
      },
    ],
  },
  {
    name: "Luxury Goods",
    slug: "luxury-goods",
    parentCategory: null,
    status: "active",
    sortOrder: 5,
    metaTitle: "Luxury Goods",
    metaDescription: "Luxury Goods Category",
    image: "/images/luxury-goods.jpg",
    subCategories: [
      {
        name: "Jewelry",
        slug: "jewelry",
        parentCategory: "Luxury Goods",
        status: "active",
        sortOrder: 1,
        metaTitle: "Jewelry",
        metaDescription: "Jewelry Category",
        image: "/images/jewelry.jpg",
      },
      {
        name: "Watches",
        slug: "watches",
        parentCategory: "Luxury Goods",
        status: "active",
        sortOrder: 2,
        metaTitle: "Watches",
        metaDescription: "Watches Category",
        image: "/images/watches.jpg",
      },
      {
        name: "Handbags",
        slug: "handbags",
        parentCategory: "Luxury Goods",
        status: "active",
        sortOrder: 3,
        metaTitle: "Handbags",
        metaDescription: "Handbags Category",
        image: "/images/handbags.jpg",
      },
    ],
  },
];
